language: node_js

node_js:
  - 12.18.1

cache:
  directories:
    - "node_modules"

# safelist
# branches:
#   only:
#   - master
#   - dev

install:
  - npm install

script:
  - npm start &
  - npm test

